### ISSUE TITLE
[Question/bug?] Subdomains

### ISSUE THREAD

**Issue by Blacksmoke16** [kvaps/docker-letsencrypt-webroot#8]
First off great work with this, is pretty dead simple to use!

I'm not sure if I am not doing something wrong or if this is a bug.

I have the image set as a service in my stack file for docker cloud.

In my case example.com is an nginx container hosting a built angular frontend.  I also have a Rails JSON API container that i have responding to api.example.com, which i also want to have encryption.  

```
letsencrypt:
  environment:
    - CHECK_FREQ=30
    - DOMAINS=example.com api.example.com
    - EMAIL=myemail@email.com
    - EXP_LIMIT=30
    - WEBROOT_PATH=/tmp/letsencrypt
  image: 'kvaps/letsencrypt-webroot:latest'
  links:
    - web
  restart: always
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '/data/letsencrypt:/etc/letsencrypt'
    - '/data/letsencrypt-www:/tmp/letsencrypt'
```

Logs from letsencrypt container.  Shows issuing a challenge for both example.com and api.example.com but in the end only issues a example.com cert, which works fine for the nginx container.
```
[letsencrypt-1]2017-11-26T03:35:21.108640660Z Obtaining a new certificate
[letsencrypt-1]2017-11-26T03:35:21.531653958Z Performing the following challenges:
[letsencrypt-1]2017-11-26T03:35:21.532831422Z http-01 challenge for example.com
[letsencrypt-1]2017-11-26T03:35:21.534335734Z http-01 challenge for api.example.com
[letsencrypt-1]2017-11-26T03:35:21.536883681Z Using the webroot path /tmp/letsencrypt for all unmatched domains.
[letsencrypt-1]2017-11-26T03:35:21.621538170Z Waiting for verification...
[letsencrypt-1]2017-11-26T03:35:25.334411946Z Cleaning up challenges
[letsencrypt-1]2017-11-26T03:35:26.008699172Z Generating key (2048 bits): /etc/letsencrypt/keys/0000_key-certbot.pem
[letsencrypt-1]2017-11-26T03:35:26.017429386Z Creating CSR: /etc/letsencrypt/csr/0000_csr-certbot.pem
[letsencrypt-1]2017-11-26T03:35:31.700125122Z IMPORTANT NOTES:
[letsencrypt-1]2017-11-26T03:35:31.700378193Z  - Congratulations! Your certificate and chain have been saved at
[letsencrypt-1]2017-11-26T03:35:31.700486646Z    /etc/letsencrypt/live/example.com/fullchain.pem. Your cert will
[letsencrypt-1]2017-11-26T03:35:31.700573412Z    expire on 2018-02-24. To obtain a new or tweaked version of this
[letsencrypt-1]2017-11-26T03:35:31.700656414Z    certificate in the future, simply run certbot again. To
[letsencrypt-1]2017-11-26T03:35:31.700746255Z    non-interactively renew *all* of your certificates, run "certbot
[letsencrypt-1]2017-11-26T03:35:31.700839370Z    renew"
```

From what I understand i need it to generate both certs in their corresponding directories to setup the ssl in nginx since wildcards cannot be used.

Thanks!
